CREATE TABLE `receive_order` (
  `receive_order_fid` bigint(20) NOT NULL AUTO_INCREMENT,
  `branch_num` int(11) DEFAULT NULL,
  `storehouse_num` int(11) DEFAULT NULL,
  `supplier_num` int(11) DEFAULT NULL,
  `receive_order_operator` varchar(50) NOT NULL,
  `receive_order_payment_date` date DEFAULT NULL,
  `receive_order_memo` varchar(250) DEFAULT NULL,
  `receive_order_state_code` int(11) NOT NULL,
  `receive_order_state_name` varchar(200) NOT NULL,
  `receive_order_creator` varchar(50) DEFAULT NULL,
  `receive_order_auditor` varchar(50) DEFAULT NULL,
  `receive_order_total_money` decimal(16,4) DEFAULT NULL,
  `receive_order_discount_money` decimal(16,4) DEFAULT NULL,
  `receive_order_due_money` decimal(16,4) DEFAULT NULL,
  `receive_order_paid_money` decimal(16,4) DEFAULT NULL,
  `receive_order_lastest_payment_date` date DEFAULT NULL,
  `receive_order_create_time` datetime DEFAULT NULL,
  `receive_order_audit_time` datetime DEFAULT NULL,
  `receive_order_bizday` char(8) DEFAULT NULL,
  `receive_order_carried` int(11) DEFAULT NULL,
  `department_num` int(11) DEFAULT NULL,
  `receive_order_operate_date` date DEFAULT NULL,
  PRIMARY KEY (`receive_order_fid`)
) ENGINE=InnoDB AUTO_INCREMENT=2490316 DEFAULT CHARSET=gbk;
